version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  setup:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Cambiar a usuario controller
          command: |
            sudo su - controller

  install_dependencies:
    executor: docker-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:vx0Myv7knLeUeNwZmStX8qvX48mCoOg6WZlbKRdpvQA"
      - run:
          name: Instalar dependencias
          command: |
            sudo su - controller -c 'cd /home/henry/meteortest-main && npm install'

  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias externas
          command: |
            sudo su - controller -c 'cd /home/henry/meteortest-main/external-controller && npm install'
      - run:
          name: Crear build de Meteor
          command: |
            sudo su - controller -c 'cd /home/henry/meteortest-main && meteor build /tmp --directory'
      - run:
          name: Copiar build y extraer
          command: |
            sudo su - controller -c 'cp /home/controller/buildController /home/controller/buildController_$(date +%Y%m%d_%H%M%S) && tar -xzvf /tmp/bundle.tar.gz -C /home/controller/buildController'

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias en el servidor
          command: |
            sudo su - controller -c 'cd /home/controller/buildController/bundle/programs/server && npm install'
      - run:
          name: Reiniciar servicio celerate-controller
          command: |
            sudo su - controller -c 'sudo systemctl restart celerate-controller'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - install_dependencies:
          requires:
            - setup
      - build:
          requires:
            - install_dependencies
      # - deploy: # Comentar esta línea para pruebas
      #     requires:
      #       - build
