version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:vx0Myv7knLeUeNwZmStX8qvX48mCoOg6WZlbKRdpvQA"
      - run:
          name: Crear archivo y escribir fecha
          command: |
            ssh -o StrictHostKeyChecking=no henry@staging-controller.furtherreach.net 'echo $(date) > /tmp/prueba.txt'
      - run:
          name: Comprimir archivo
          command: |
            ssh -o StrictHostKeyChecking=no henry@staging-controller.furtherreach.net 'tar -czvf /tmp/prueba.tar.gz /tmp/prueba.txt'

workflows:
  version: 2
  build:
    jobs:
      - build
