version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:vx0Myv7knLeUeNwZmStX8qvX48mCoOg6WZlbKRdpvQA"
      - run:
          name: Clonar repositorio y cambiar a usuario controller
          command: |
            ssh -o StrictHostKeyChecking=no henry@staging-controller.furtherreach.net << 'EOF'
              sudo su - controller
              cd /home/henry/meteortest-main
              git pull origin main
            EOF
      - run:
          name: Instalar dependencias
          command: |
            ssh -o StrictHostKeyChecking=no henry@staging-controller.furtherreach.net << 'EOF'
              sudo su - controller
              cd /home/henry/meteortest-main
              npm install
            EOF
      - run:
          name: Instalar dependencias externas
          command: |
            ssh -o StrictHostKeyChecking=no henry@staging-controller.furtherreach.net << 'EOF'
              sudo su - controller
              cd /home/henry/meteortest-main/external-controller
              npm install
            EOF
      - run:
          name: Crear build de Meteor
          command: |
            ssh -o StrictHostKeyChecking=no henry@staging-controller.furtherreach.net << 'EOF'
              sudo su - controller
              cd /home/henry/meteortest-main
              meteor build /tmp --directory
            EOF
      - run:
          name: Copiar build y extraer
          command: |
            ssh -o StrictHostKeyChecking=no henry@staging-controller.furtherreach.net << 'EOF'
              sudo su - controller
              cp /home/controller/buildController /home/controller/buildController_$(date +%Y%m%d_%H%M%S)
              tar -xzvf /tmp/bundle.tar.gz -C /home/controller/buildController
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      # - deploy: # Comentar esta línea para pruebas
      #     requires:
      #       - build
