version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:vx0Myv7knLeUeNwZmStX8qvX48mCoOg6WZlbKRdpvQA"
      - run:
          name: Clonar repositorio y cambiar a usuario controller
          command: |
            ssh -o StrictHostKeyChecking=no henry@staging-controller.furtherreach.net 'sudo su - controller -c "cd /home/henry/meteortest-main && git pull origin main"'
      - run:
          name: Instalar dependencias
          command: |
            ssh -o StrictHostKeyChecking=no henry@staging-controller.furtherreach.net 'sudo su - controller -c "cd /home/henry/meteortest-main && npm install"'
      - run:
          name: Instalar dependencias externas
          command: |
            ssh -o StrictHostKeyChecking=no henry@staging-controller.furtherreach.net 'sudo su - controller -c "cd /home/henry/meteortest-main/external-controller && npm install"'
      - run:
          name: Crear build de Meteor
          command: |
            ssh -o StrictHostKeyChecking=no henry@staging-controller.furtherreach.net 'sudo su - controller -c "cd /home/henry/meteortest-main && meteor build /tmp --directory"'
      - run:
          name: Copiar build y extraer
          command: |
            ssh -o StrictHostKeyChecking=no henry@staging-controller.furtherreach.net 'sudo su - controller -c "cp -r /home/controller/buildController /home/controller/buildController_$(date +%Y%m%d_%H%M%S) && tar -xzvf /tmp/bundle.tar.gz -C /home/controller/buildController"'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      # - deploy: # Comentar esta línea para pruebas
      #     requires:
      #       - build
