version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
      - run:
          name: Build Project
          command: |
            echo "Building project"
            # Aquí van tus comandos de construcción y pruebas
      - run:
          name: Send Webhook
          command: |
            curl -X POST -H "Content-Type: application/json" -d '{"status":"success"}' http://your-server-endpoint/deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
