name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Restart PM2 process
        run: pm2 restart all

      - name: Notify deployment status
        run: echo "Deployment completed successfully!"

