name: Deploy to Meteor Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run restartService.sh
        run: sudo -u xanadu /bin/bash /home/xanadu/restartService.sh
        user: xanadu

