name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and restart service
        run: |
          cd /path/to/project
          npm install
          pm2 restart 0

      - name: Notify deployment status
        run: echo "Deployment completed successfully!"

