name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install pm2
        run: npm install -g pm2

      - name: Restart server
        run: ./home/xanadu/meteortest/restartService.sh

