name: Build and Transfer

on:
  push:
    branches:
      - develop
      - pre-prod
      - prod

jobs:
  build_and_transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 staging-controller.furtherreach.net >> ~/.ssh/known_hosts

      - name: Set environment variables based on branch
        run: |
          branch_name=${{ github.ref_name }}
          case "$branch_name" in
            "develop")
              echo "SERVER_URL=${{ secrets.DEVELOP_URL }}" >> $GITHUB_ENV
              echo "SERVER_USER=${{ secrets.DEVELOP_USER }}" >> $GITHUB_ENV
              ;;
            "pre-prod")
              echo "SERVER_URL=${{ secrets.PRE_PROD_URL }}" >> $GITHUB_ENV
              echo "SERVER_USER=${{ secrets.PRE_PROD_USER }}" >> $GITHUB_ENV
              ;;
            "prod")
              echo "SERVER_URL=${{ secrets.PROD_URL }}" >> $GITHUB_ENV
              echo "SERVER_USER=${{ secrets.PROD_USER }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown branch: $branch_name"
              exit 1
              ;;
          esac

      - name: Install Meteor
        run: |
          curl https://install.meteor.com/ | sh

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          meteor build --directory /tmp/build --server-only --allow-superuser

      - name: Archive and transfer build to server
        run: |
          tar -czf - -C /tmp build | ssh -p 22 -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_URL }} 'cat > /tmp/build.tar.gz'
