name: List secrets and variables

on:
  push:
    branches:
      - main

jobs:
  list-secrets-and-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print LOCAL_SSH_KEY secret (Will not print value, only asterisks)
        run: echo "LOCAL_SSH_KEY: ${{ secrets.LOCAL_SSH_KEY }}"

      - name: Print LOCAL environment variable
        run: echo "LOCAL: $LOCAL"
        env:
          LOCAL: ${{ env.LOCAL }}

      - name: Ensure secrets and env variables are accessible
        run: |
          echo "Ensuring secrets and env variables are accessible"
          echo "LOCAL_SSH_KEY: ${{ secrets.LOCAL_SSH_KEY }}"
          echo "LOCAL: ${{ env.LOCAL }}"
