name: Print Secrets and Variables

on:
  push:
    branches:
      - main

jobs:
  list-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List environment secrets
        run: |
          echo "Listing environment secrets..."
          echo "${{ toJSON(secrets) }}"

      - name: List environment variables
        run: |
          echo "Listing environment variables..."
          env
