name: Print Specific Secrets and Variables

on:
  push:
    branches:
      - main

jobs:
  list-specific-secrets-and-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print LOCAL_SSH_KEY (Will not print value, only asterisks)
        run: |
          echo "LOCAL_SSH_KEY: ${{ secrets.LOCAL_SSH_KEY }}"

      - name: Print LOCAL environment variable
        run: |
          echo "LOCAL: ${{ env.LOCAL }}"
