name: List secrets and variables

on:
  push:
    branches:
      - main

jobs:
  list-secrets-and-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print LOCAL_SSH_KEY secret
        run: |
          echo "LOCAL_SSH_KEY: [hidden]"
          echo ${{ secrets.LOCAL_SSH_KEY }}

      - name: Print LOCAL environment variable
        env:
          LOCAL: ${{ secrets.LOCAL }}
        run: |
          echo "LOCAL: $LOCAL"
