name: List Secrets and Environment Variables

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  list_secrets_and_env:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: List Environment Secrets
        run: |
          echo "Listing environment secrets..."
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          # Agrega más secretos si es necesario

      - name: List Environment Variables
        run: |
          echo "Listing environment variables..."
          printenv
